### ISSUE TITLE
TypeError: Cannot read property 'stateMachines' of undefined when starting step functions

### ISSUE THREAD

**Issue by vharigandhi** [flocasts/serverless-offline-step-functions#11]
Getting the following error while calling stepFunctions.startExecution
```
node_modules\serverless-offline-step-functions\src\step-functions-api-simulator.js:32
            _.forEach(serverless.service.stepFunctions.stateMachines, (machine, machineKey) => {
                                                       ^
TypeError: Cannot read property 'stateMachines' of undefined
    at IncomingMessage.req.on (c:\Users\<user-home>\Source\GlobalRecruitTrans_20224_Candidate_Data_Ingester\node_modules\serverless-offline-step-functions\src\step-functions-api-simulator.js:32:56)
    at IncomingMessage.emit (events.js:194:15)
    at IncomingMessage.EventEmitter.emit (domain.js:441:20)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Below is my step function configuration:
```
stepFunctions:
  stateMachines:
    MY_ORCHESTRATOR:
      name: MY_ORCHESTRATOR_STATE_MACHINE_${opt:stage, self:custom.defaultStage}
      role: ${file(./config/serverless.config.${opt:stage, self:custom.defaultStage}.yml):stepFunctionIamRole}
      definition:
        Comment: "Parse Resume and send data to NiFi"
        StartAt: ParseCV
        States:
          ParseCV:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:STEP_FN1_${opt:stage, self:custom.defaultStage}
            Next: PostToNiFi
          PostToNiFi:
            Type: Task
            Resource: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:STEP_FN2_${opt:stage, self:custom.defaultStage}
            End: true
```

**Comment by vharigandhi** [comment]
I am trying to trigger a lambda when a file is uploaded to S3 bucket which will in turn start the step functions. Below is the plugins configuration:

```
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-s3-local
  - serverless-pseudo-parameters
  - serverless-step-functions
  - serverless-offline-step-functions 
```

**Comment by karopolopoulos** [comment]
Hi @vharigandhi old thread so you probably figured it out but I believe that changing the order of your plugins resolves this issue. You will want to do:

```
plugins:
  - serverless-step-functions
  - serverless-offline-step-functions
  - serverless-offline

**Comment by alsenydiallo** [comment]
has there been a resolution to this thread ?

**Comment by lagnat** [comment]
Note that this project is no longer being maintained and this repo will likely get archived in the near future.
