### ISSUE TITLE
Error: ENOENT: no such file or directory, open './node_modules/serverless-offline-step-functions/src/step-functions.json' when installed in monorepo project

### ISSUE THREAD

**Issue by tan-t** [flocasts/serverless-offline-step-functions#22]
## Description
when ```sls offline ``` within lerna monorepo environment,  
it throws an error like below:  
```
 Error: ENOENT: no such file or directory, open './node_modules/serverless-offline-step-functions/src/step-functions.json'
      at Object.openSync (fs.js:458:3)
      at Object.writeFileSync (fs.js:1355:35)
      at ServerlessPlugin.createStepFunctionsJSON (***/stepfunctions-monorepo-example/node_modules/serverless-offline-step-functions/index.js:143:8)
      at ServerlessPlugin.tryCatcher (***/stepfunctions-monorepo-example/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (***/stepfunctions-monorepo-example/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (***/stepfunctions-monorepo-example/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (***/stepfunctions-monorepo-example/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (***/stepfunctions-monorepo-example/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (***/stepfunctions-monorepo-example/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (***/stepfunctions-monorepo-example/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (***/stepfunctions-monorepo-example/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (***/stepfunctions-monorepo-example/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

## Expected Behavior
starts without exception.  

## Possible Fix
it is mainly caused by the node_modules path resolation.  
I will make a PR about this.

## Steps to Reproduce
1. make a project with https://github.com/lerna/lerna lerna. the structure will be like this:  
```
.
├── lerna.json
├── node_modules
├── package.json
├── packages
│   ├── backend
│   │   ├── package.json
│   │   └── serverless.yml
│   └── frontend
```
2. install this package into packages/backend. the package will be placed in **node_modules**, not **packages/backend/node_modules**.
3. kick ```sls offline ``` inside packages/backend.

## Your Environment
I've created a simple example repo to reproduce this issue.  
https://github.com/srac-technologies/stepfunctions-monorepo-example

**Comment by tan-t** [comment]
update: this PR https://github.com/flocasts/serverless-offline-step-functions/pull/17  
seems to solve this issue. so I won't make a PR related to this.
